  printf("                                           1)Print Hello World                                       \n");
  printf("                                           2)Add Two Numbers                                         \n");
  printf("                                           3)whether the given number is a prime or not              \n");
  printf("                                           4)Check Alphabet or Not                                   \n");
  printf("                                           5)Check Alphabet or Not                                   \n");
  printf("                                           6)Check Vowel or Not                                      \n");
  printf("                                           7)Check Leap Year or No                                   \n");
  printf("                                           8)Check Reverse is Equal to its Original or Not           \n");
  printf("                                           9)Addition, Subtraction, Multiplication, and Division     \n");
  printf("                                           10)Simple Calculator                                      \n");
  printf("                                           11)sum of all digit of that number along with the number itself \n");
  printf("                                           12)Calculate Average and Percentage Marks                 \n");
  printf("                                           13)Calculate Arithmetic Mean                               \n");
  printf("                                           14)Calculate Grade of Student                                \n");
  printf("                                           15)print the table of that number                                   \n");
  printf("                                           16)print all prime number from 1 to 50                          \n");
  printf("                                           17)Add n Numbers                             \n");
  printf("                                           18)Interchange Two Numbers                                    \n");
  printf("                                           19)Reverse Number                                   \n");
  printf("                                           20)Count Occurrence of Positive, Zero, and Negative Numbers                             \n");
  printf("                                           21)find largest or greatest between any two                               \n");
  printf("                                           22)largest of any given three numbers by user                                   \n");
  printf("                                           23)calculate and print the factorial of any given number                                   \n");
  printf("                                           24)Find HCF and LCM of Two Numbers                                   \n");
  printf("                                           25)area and perimeter of rectangle                                \n");
  printf("                                           26)Calculate Area and Circumference of Circle                                \n");
  printf("                                           27)Fahrenheit to Centigrade Conversion                                 \n");
  printf("                                           28)Centigrade to Fahrenheit Conversion                                   \n");
  printf("                                           29)Print ASCII Values of Characters                                \n");
  printf("                                           30)Fibonacci series                                   \n");
  printf("                                           31)Check Palindrome or Not                       \n");
  printf("                                           32)check if original number is equal to its reverse                                   \n");
  printf("                                           33) 1+(1+2)+(1+2+3).....                              \n");
  printf("                                           34)sum of all values in an array                                 \n");
  printf("                                           35)check sub string is present in string or not                              \n");
  printf("                                           36)convert decimal number to binary equivalent                                   \n");
  printf("                                           37)selection sort                                  \n");
  printf("                                           38)sum of elements of even indices                            \n");
  printf("                                           39)sum of odd indices                                   \n");
  printf("                                           40)delete the specified integer from the list                               \n");
  printf("                                           41)Diamond Pattern                                 \n");
  printf("                                           42)Binary Search                                   \n");
  printf("                                           43)Bubble Sort                             \n");
  printf("                                           44)Selection sort                                \n");
  printf("                                           45)merge any two arrays                                   \n");
  printf("                                           46)add any two 3*3 matrix.                                   \n");
  printf("                                           47)Subtract Matrices                                   \n");
  printf("                                           48)Transpose Matrix                                   \n");
  printf("                                           49)multiply two 3*3 matrices                             \n");
  printf("                                           50)print string back on the output screen                                  \n");
  printf("                                           51)find and print the length of any given string                                 \n");
  printf("                                           52)Compare Two Strings                                \n");
  printf("                                           53)copy string                                 \n");
  printf("                                           54)print given string in reverse order without reversing it                                  \n");
  printf("                                           55)concatenate strings                            \n");
  printf("                                           56)Delete Vowels from String                                  \n");
  printf("                                           57)Convert Uppercase Character to Lowercase                                  \n");
  printf("                                           58)find frequency of any given character                              \n");
  printf("                                           59)Count Occurrence of Words in Sentence                               \n");
  printf("                                           60)Remove Spaces from String                                   \n");
  printf("                                           61)print lower case character to uppercase                                   \n");
  printf("                                           62)string reversal                                   \n");
  printf("                                           63)swapping n number of times                               \n");
  printf("                                           64)string length                               \n");
  printf("                                           65)pallindrome                                   \n");
  printf("                                           66)fibonacci                                   \n");
  printf("                                           67)frequency of caharacter                                \n");
  printf("                                           68)primary diagonal                                   \n");
  printf("                                           69)secondary diagonal                                   \n");
  printf("                                           70)upper triangle                             \n");
  printf("                                           71)lower triangle                                \n");
  printf("                                           72)sum of primary diagonal                                  \n");
  printf("                                           73)sum of row                            \n");
  printf("                                           74)smallest element of row                                   \n");
  printf("                                           75)largest element off row                                  \n");
  printf("                                           76)delete duplicates                                   \n");
  printf("                                           77)check for positive negative and zero                                  \n");
  printf("                                           78)basic pay                                   \n");
  printf("                                           79)delete from particular position                                   \n");
  printf("                                           80)check if strings are equal                              \n");
  printf("                                           81)pattern 1                                 \n");
  printf("                                           82)pattern 2                                   \n");
  printf("                                           83)pattern 3                               \n");
  printf("                                           84)pattern 4                              \n");
  printf("                                           85)pattern 5                                  \n");
  printf("                                           86)pattern 6                               \n");
  printf("                                           87)pattern 7                                  \n");
  printf("                                           88)pattern 8                               \n");
  printf("                                           89)prime check                                  \n");
  printf("                                           90)square root                                   \n");
  printf("                                           91)swapping                                  \n");
  printf("                                           92)no. of words in a string                                   \n");
  printf("                                           93)                                   \n");
  printf("                                           94)                                   \n");
  printf("                                           95)                                   \n");
  printf("                                           96)                                   \n");
  printf("                                           97)                                  \n");
  printf("                                           98)                                  \n");
  printf("                                           99)                                 \n");
  printf("                                           100)                                  \n");
